require"user.colorscheme.default"
require"user.colorscheme.transparent"
-- require"user.colorscheme.rainbow"
require"user.colorscheme.settings"
-- require"user.colorscheme.synstack"
require"user.colorscheme.overrides"
